{
 "title": "Blackbox Exporter 监控展示看板",
 "tags": [
  "Prometheus",
  "blackbox_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "blackbox",
    "query": "label_values(probe_success,instance)"
   },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*\"},job)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "检测总耗时 $targets",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP检测类服务状态统计",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code)",
     "legendFormat": "http status {{ value }}"
    }
   ]
  },
  {
   "title": "服务连通性统计",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{job=~'$job'})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS检测类 阶段耗时 $targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{job=~'$job',instance=~'$targets'}",
     "legendFormat": "{{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "$job Blackbox 状态明细",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$targets\"}-time()"
    }
   ]
  }
 ]
}